### ISSUE TITLE
Problem DCCP status and some numerical(?) errors

### ISSUE THREAD

**Issue by mbilalzafar** [cvxgrp/dccp#11]
Hello. I try an optimization problem with constraints of the form `f1 - f2 == 0` (where both `f1` and `f2` are convex), and I get an error saying :

> not a dccp problem

I reformulate the constraint to `f1 == f2` and I get a solution.

The above solution works well for some cases. However, in some other cases, the constraint `f1 == f2` does not give me the expected solution (the returned solution does not satisfy the specified constraint). However, reforming the same constraint as `1^6 * f1 == 10^6 * f2`, that is, just multiplying both sides with big numbers gives a solution which is perfectly fine. Maybe its due to some error in floating point operations?

Thanks in advance for the help!

**Comment by jaehyunp** [comment]
I think the latter part is indeed due to scale of the problem. The first part is a bit tricky. Currently, dccp detects a constraint as a valid dccp constraint if both sides of the (in)equality constraint are dcp (what cvxpy recognizes as convex or concave). However, if you explicitly write the difference f1-f2 as the left hand side, all that the system sees is a single expression with unknown curvature, and it doesn't know how to separate it out as a difference of convex expression.

**Comment by mbilalzafar** [comment]
Thanks for the quick reply!

While checking with is_dcp() method, both `f1` and `f2` are deemed DCP by cvxpy. So according to Eq. 1 here (http://stanford.edu/~boyd/papers/pdf/dccp.pdf), shouldn't the DCCP package be able to solve the difference of two DCP functions (`f1 - f2 == 0`)?

About the second part, I checked and the results vary significantly based on the 'big' number that I multiply the constraints with (10^3, 10^6, etc). For some problems, I need to multiply the constraints with a rather big number, however, if the number is too big, I get an error saying that the solver was unable to solve the problem. Could you please suggest a workaround here? Maybe its a matter of using high precision floating point numbers (numpy.float64) in the solver? 

BTW, the numbers that I am dealing with are not THAT small anyway, so maybe the error is coming from somewhere else (e.g., some stopping threshold)?

**Comment by SteveDiamond** [comment]
You're right that conventionally difference-of-convex programs are framed as ``convex  - convex == 0`` (hence the name), but as you can see in Eq. 2 _disciplined_ difference-of-convex programs are not expressed this way. Instead, each side of the constraint must satisfy the DCP rules, so you write ``f1 == f2``.

You're quite right that the rescaling is not so much a numerical issue as a hyperparameter selection issue. Scaling the constraints is equivalent to increasing tau0 in Algorithm 1.1. You should try playing with the parameters tau0, tau_max, and mu in
https://github.com/cvxgrp/dccp/blob/master/dccp/problem.py

**Comment by jaehyunp** [comment]
I can see how this is confusing. DCCP is essentially a restriction of general difference-of-convex programming, because it is, in general, impossible to automatically split a difference-of-convex function into the convex and concave parts. The DCCP rules are given in Section 1.3 of the paper, not in equation (1). What equation (1) defines is the concept of difference-of-convex programming.

**Comment by mbilalzafar** [comment]
Makes sense. Thanks a lot for the clarifications!
