### ISSUE TITLE
Failed for a simple case

### ISSUE THREAD

**Issue by yujiadeng** [cvxgrp/dccp#35]
Hi,

I'm testing with the following case
```
import cvxpy as cvx
import dccp
x = cvx.Variable(1)
myprob = cvx.Problem(cvx.Minimize(x**4-3*x**2-x), [0<=x, x<=2])
print("problem is DCP:", myprob.is_dcp())  
print("problem is DCCP:", dccp.is_dccp(myprob))

result = myprob.solve(method = 'dccp', verbose=True)
print("x =", x.value)
print("cost value =", result[0]) 
```
The function looks like the following
![image](https://user-images.githubusercontent.com/27870225/53824555-d0c88a00-3f39-11e9-91df-76cd21bf3fab.png)
and should reach the minimum at around x=1.33.

However the above code always returns x at boundary. Am I doing something wrong?

**Comment by xinyueshen** [comment]
Hello @yujiadeng, the objective function is required to be either convex or concave, so in your case the code should be as follows.

```import cvxpy as cvx
import dccp
x = cvx.Variable(1)
y = cvx.Variable(1)

myprob = cvx.Problem(cvx.Minimize(x**4-y-x), [0 <= x, x <= 2, y == 3*x**2])
print("problem is DCP:", myprob.is_dcp())
print("problem is DCCP:", dccp.is_dccp(myprob))

result = myprob.solve(method='dccp', verbose=True, tau=1.0, mu=1.001)
print("x =", x.value)
print("3x^2 = ", 3*x.value**2)
print("y = ", y.value)
print("cost value =", result[0])```

**Comment by yujiadeng** [comment]
Thanks for your reply! I copied and ran the code, and the result is as follows:
```
x = [0.62997096]
3x^2 =  [1.19059024]
y =  [-1.19058259]
cost value = 0.7181121954947433
```
Not quite sure why y has the negative sign here... and the solution looks not consistent with the funtion plot...

I also tried different constraints on x with `myprob = cvx.Problem(cvx.Minimize(x**4-y-x), [-2 <= x, x <= 0, y == 3*x**2])` and it yields
```
x = [-1.0491784e-11]
3x^2 =  [3.30232593e-22]
y =  [2.64096419e-08]
cost value = -2.6399150107911523e-08
```
Looks it doesn't converge to the local minimum on the left half x axis.

**Comment by xinyueshen** [comment]
@yujiadeng I see. I'm looking into it, and will get to you as soon as I fix it.

**Comment by xinyueshen** [comment]
Hi @yujiadeng, I just fixed some bugs, so now it works, and I can get the following result by running the code in my previous reply.
```
('problem is DCP:', False)
('problem is DCCP:', True)
('x =', array([1.30065779]))
('3x^2 = ', array([5.07513209]))
('y = ', array([5.07513212]))
('cost value =', -3.5139048310022165)

Note that it gives a more accurate result than `x=1.33`.

**Comment by yujiadeng** [comment]
It works for me, thanks!

Yet I'm still curious about its behaviour on $x\leq 0$. I tried varying the upper bound of the constraints with `range(-0.5, 0.01, 0.01)` and plot the solution. Following are the results of two repetitions.
![image](https://user-images.githubusercontent.com/27870225/53891869-d7660880-3ff0-11e9-81ea-02df1be7a54c.png)
![image](https://user-images.githubusercontent.com/27870225/53891878-dfbe4380-3ff0-11e9-8530-9d876807bc03.png)

Looks like the solution becomes unstable after the upper bound passes -0.16, where the convexity of the curve changes, especially for 0. I further repeat for 50 times for upper bound=0 and the result looks like below:
![image](https://user-images.githubusercontent.com/27870225/53892629-43953c00-3ff2-11e9-8167-bf0c97aa298a.png)

 I'm wondering if dccp is supposed to be able to deal with this. Or is it just this function?

**Comment by xinyueshen** [comment]
DCCP is supposed to provide results for convex-concave problems using a local and efficient method, but theoretically it does not guarantee to find a global optimum. In practice, the result is highly dependent on the initialization of the program. If the user does not initialize the variables with specific values, which is our case now, DCCP uses randomly generated initialization. Thus, you got different results (when you repeated the experiment for 50 times) because of the randomness of the initialization. 

However, if you give an initial value to `x`, e.g. having `x.value = -10` everytime before running `result = myprob.solve(method='dccp', verbose=True, tau=1.0, mu=1.001)`, then DCCP will use this specified initialization instead of the random one.

I just tried the initial value `x.value = -10`, for the upper bound of the constraint in the range of `range(-0.5, 0.01, 0.01)`, it always returns `x.value = -1.1317` as the result.

**Comment by yujiadeng** [comment]
That makes sense. Thanks for the detailed explanation!
