### ISSUE TITLE
Is there any difference between equality and inequality constraint?

### ISSUE THREAD

**Issue by zhuwang46** [cvxgrp/dccp#40]
https://github.com/cvxgrp/dccp/blob/03dc117595554421f5d05227bf5e5a1c8712411e/examples/ML_cov_est.py

The code uses trace_val<=t. But it works with trace_val=t as well. What's the difference? In fact, in the paper https://arxiv.org/pdf/1604.02639.pdf , on page 4, “subject to t=g_0(x)” is what states. Hence, one should use trace_val=t.

**Comment by xinyueshen** [comment]
Hi @zhuwang46, on page 4 of the paper "t = g_0(x)" shows that with a simple variable substitution problem (1) can be expressed in the form of problem (2). In the covariance matrix estimation example, the problem with "trace_val <= t" and the problem with "trace_val == t" have same global solutions, so you can try either of them, but using "trace_val <= t" could bring less burden to the solver, since it is already a convex constraint and does not need further convexification.
