### ISSUE TITLE
CCP constraints raise  an error

### ISSUE THREAD

**Issue by jdebecdelievre** [cvxgrp/dccp#49]
Hello,

Here is the simplest (dummy) problem representing the issue I have:

```
import cvxpy as cp
import dccp
z = cp.Variable(1)
obj = cp.Minimize(z)
con = [cp.power(z,2) >= 0., z<=1., z>=0.]
prob = cp.Problem(obj, con)
assert dccp.is_dccp(prob)
prob.solve(method='dccp', solver='ECOS')
```
The error I get is:

`TypeError: cannot unpack non-iterable NotImplementedType object`

Do you know where this could be from?
Thank you!

**Comment by xinyueshen** [comment]
Hi @jdebecdelievre, I think DCCP or CVXPY was not correctly installed in your case. Did you install DCCP from source?

**Comment by gioperin** [comment]
Hi @xinyueshen, apologize for multiple posting (I opened issue #51). I have the same problem, I also tried the example posted by @jdebecdelievre and I got the same error. I installed DCCP from pip and I'm using it inside a conda environment. However, everything is up to date since I updated both cvxpy and dccp yesterday.

**Comment by xinyueshen** [comment]
Thanks for pointing it out. For solution please see issue #51.
